name: Build alpha

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install pygame pyinstaller requests Pillow customtkinter

      - name: Build with PyInstaller on Windows
        if: runner.os == 'Windows'
        run: pyinstaller --onefile --name game --add-data "assets;assets" --hidden-import PIL._tkinter_finder main.py

      - name: Build with PyInstaller on Linux
        if: runner.os == 'Linux'
        run: pyinstaller --onefile --name game --add-data "assets:assets" --hidden-import PIL._tkinter_finder main.py

      - name: Upload artifact - Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: game.exe
          path: dist/game.exe

      - name: Upload artifact - Linux
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: game
          path: dist/game
