name: Build alpha

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install pygame nuitka requests Pillow customtkinter

      - name: Build with Nuitka on Windows
        if: runner.os == 'Windows'
        run: |
          python -m nuitka --onefile --jobs=1 --windows-icon-from-ico=assets/potato.ico --include-data-dir=assets=assets --assume-yes-for-downloads main.py
          if (!(Test-Path dist)) { New-Item -ItemType Directory -Path dist }
          Move-Item main.exe dist/game.exe

      - name: Build with Nuitka on Linux
        if: runner.os == 'Linux'
        run: |
          python -m nuitka --onefile --include-data-dir=assets=assets main.py
          mkdir -p dist
          mv main.bin dist/game

      - name: Upload artifact - Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: game.exe
          path: dist/game.exe

      - name: Upload artifact - Linux
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: game
          path: dist/game
