name: Build game on release tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-ccache-${{ hashFiles('requirements.txt') }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/Nuitka
            C:\Users\runneradmin\AppData\Local\pip\Cache
            C:\Users\runneradmin\AppData\Local\Nuitka\Cache
          key: ${{ runner.os }}-nuitka-${{ hashFiles('requirements.txt') }}

      - run: pip install -r requirements.txt

      - name: Build with Nuitka on Windows
        if: runner.os == 'Windows'
        run: python -m nuitka --onefile --jobs=1 --python-flag=no_docstrings --output-dir=dist --output-filename="Skakavi-Krompir-Windows" --windows-icon-from-ico=assets/potato.ico --include-data-dir=assets=assets --assume-yes-for-downloads --enable-plugin=tk-inter --lto=no main.py

      - name: Build with Nuitka on Linux
        if: runner.os == 'Linux'
        run: python -m nuitka --onefile --jobs=$(nproc) --python-flag=no_docstrings --output-dir=dist --output-filename="Skakavi-Krompir-Linux" --include-data-dir=assets=assets --enable-plugin=tk-inter --static-libpython=yes main.py

      - name: Create .deb package on Linux
        if: runner.os == 'Linux'
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          APP_NAME="Skakavi Krompir"
          APP_ID="skakavi-krompir"
          DEBIAN_PACKAGE_DIR="debian_package"
          
          # Create directory structure
          mkdir -p ${DEBIAN_PACKAGE_DIR}/DEBIAN
          mkdir -p ${DEBIAN_PACKAGE_DIR}/usr/local/bin
          mkdir -p ${DEBIAN_PACKAGE_DIR}/usr/share/applications
          mkdir -p ${DEBIAN_PACKAGE_DIR}/usr/share/pixmaps

          # Copy executable
          cp dist/Skakavi-Krompir-Linux ${DEBIAN_PACKAGE_DIR}/usr/local/bin/${APP_ID}

          # Create control file
          cat <<EOF > ${DEBIAN_PACKAGE_DIR}/DEBIAN/control
          Package: ${APP_ID}
          Version: ${VERSION}
          Architecture: amd64
          Maintainer: user <user@example.com>
          Description: A Flappy Bird-like game.
           Skakavi Krompir is a simple game where you control a potato and try to avoid obstacles.
          Depends: libc6 (>= 2.35)
          EOF

          # Create desktop entry
          cat <<EOF > ${DEBIAN_PACKAGE_DIR}/usr/share/applications/${APP_ID}.desktop
          [Desktop Entry]
          Name=${APP_NAME}
          Exec=/usr/local/bin/${APP_ID}
          Icon=/usr/share/pixmaps/${APP_ID}.png
          Type=Application
          Categories=Game;
          EOF

          # Copy icon
          cp assets/potato.png ${DEBIAN_PACKAGE_DIR}/usr/share/pixmaps/${APP_ID}.png

          # Build the .deb package. Output directly to dist folder.
          dpkg-deb --build ${DEBIAN_PACKAGE_DIR} dist/${APP_ID}_${VERSION}_amd64.deb

      - uses: actions/upload-artifact@v4
        with:
          name: game-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag message
        id: get_tag_message
        run: echo "message=$(git tag -l --format='%(contents:subject)' ${{ github.ref }})" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v4
        with:
          path: dist

      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.get_tag_message.outputs.message }}
          files: |
            dist/game-windows-latest/*
            dist/game-ubuntu-22.04/*
